project:
  type: website
  resources:
    - js/particles-config.json
    - assets/Jones_2025_Resume_v2.pdf
    - assets/Connor_Jones_Resume.pdf
    - assets/sf_selfie_pic.jpg


website:
  title: "Connor Jones"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd

format:
  html:
    theme: darkly
    page-layout: full
    lightbox: true
    theme-toggle: false
    fontfamily: "Oswald, serif"
    toc: true
    embed-resources: true



